-- # --- !Ups
--
-- create table "people" (
--   "id" bigint generated by default as identity(start with 1) not null primary key,
--   "name" varchar not null,
--   "age" int not null
-- );
--
-- # --- !Downs
--
-- drop table "people" if exists;
--

-- MySQL --

# --- !Ups

CREATE TABLE people(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(25) NOT NULL,
age INT NOT NULL
);

# --- !Downs
--
DROP TABLE IF EXISTS people;
